CAMERA_INDEX = 0
WINDOW_NAME = "Airpainter"

BRUSH_COLOR = (0, 0, 0)
BRUSH_THICKNESS = 6
DRAW_RADIUS = 10

SMOOTHING_POINTS = 5
GESTURE_SMOOTHING_FRAMES = 4
FINGER_Y_MARGIN = 0.02

MAX_NUM_HANDS = 1
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5
